name: github-actions
on: push
jobs:
  check-bats-version:
    runs-on: 
      group: ubuntu-runners
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo "Hello, world!"
