name: CI/CD with Docker

on: [push]

jobs:
  workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t my-app .

      - name: run tests
        run: |
          docker build -t my-app-test -f Dockerfile.test .
          docker run --rm my-app-test

      - name: Deploy 
        run: docker run --rm my-app






