name: CI/CD with Docker

on: [push]

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t my-app .

      - name: Run tests 
        run: echo "test successful (simulation)"

      - name: Check Docker Compose version
        run: docker compose versio

      - name: Deploy (simulate)
        run: docker compose up -d
