name: demo-workflow
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print to console
        run: echo Hello, world!
      - name: Get repository code
        run: actions/checkout@v4
